name: Python Code Quality Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint pytest
        pip install .
    
    - name: Check code formatting with Black
      run: |
        black --check --diff .
    
    - name: Run Pylint
      run: |
        pylint $(git ls-files '*.py') --disable=C0301,R0913,R0914
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v

  build-success:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
    - name: Build success
      run: echo "All code quality checks passed!"