name: Deploy Documentation

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    if: github.repository_owner == 'Qiskit-Community'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"

    - name: Build documentation
      run: |
          cd docs
          make html SPHINXOPTS="--keep-going"

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/_build/html/